/**
 * validation/SQLValidator.ts
 *
 * The SQLValidator is the security gatekeeper of the nlsql library.
 * Before any LLM-generated SQL is allowed to execute against the database,
 * it must pass through this class.
 *
 * It uses a two-tier approach:
 *
 *   Tier 1 — Keyword Blocklist:
 *     A fast regular-expression scan for dangerous keywords (INSERT, DELETE,
 *     DROP, etc.). Catches obvious threats in microseconds.
 *
 *   Tier 2 — Structural Analysis:
 *     A deeper parse of the SQL structure to ensure it starts with SELECT
 *     and contains no data-changing operations, even if they are hidden in
 *     subqueries or disguised with unusual formatting.
 *
 * Both tiers must pass. If either rejects the query, it never reaches the DB.
 */

import type { ValidationResult } from '../types';

/**
 * SQLValidator checks LLM-generated SQL for safety before execution.
 *
 * It enforces a strict READ-ONLY policy: only SELECT statements are allowed.
 * Any query that could create, modify, or delete data is rejected.
 *
 * @example
 * const validator = new SQLValidator();
 *
 * const result = validator.validate('SELECT id FROM users');
 * // result.isValid === true
 *
 * const result2 = validator.validate('DROP TABLE users');
 * // result2.isValid === false
 * // result2.reason  === "Blocked keyword detected: DROP"
 */
export class SQLValidator {
  /**
   * A list of SQL keywords that indicate data-mutating or schema-altering
   * operations. Any SQL containing these words (as whole words, case-insensitive)
   * is immediately rejected.
   *
   * We use word-boundary matching (\b) so that a column named "insertion_date"
   * does NOT trigger the INSERT block, but "INSERT INTO" does.
   */
  private static readonly BLOCKED_KEYWORDS: string[] = [
    'INSERT',
    'UPDATE',
    'DELETE',
    'DROP',
    'TRUNCATE',
    'ALTER',
    'CREATE',
    'REPLACE',
    'RENAME',
    'GRANT',
    'REVOKE',
    'CALL',
    'EXEC',
    'EXECUTE',
    'LOAD',
    'INTO OUTFILE',
    'INTO DUMPFILE',
  ];

  /**
   * Pre-compiled regular expression built from BLOCKED_KEYWORDS.
   * Compiled once at construction time for performance.
   * The \b...\b notation means "whole word only".
   */
  private readonly blockedPattern: RegExp;

  /**
   * Creates a new SQLValidator instance.
   * Construction is lightweight — the regex is compiled once and reused.
   */
  constructor() {
    // Build one combined regex from all blocked keywords.
    // Example result: /\b(INSERT|UPDATE|DELETE|DROP|...)\b/gi
    const pattern = SQLValidator.BLOCKED_KEYWORDS
      .map((kw) => kw.replace(/\s+/g, '\\s+')) // handle multi-word keywords
      .join('|');
    this.blockedPattern = new RegExp(`\\b(${pattern})\\b`, 'gi');
  }

  /**
   * Validates a SQL string for safety.
   *
   * Runs both validation tiers in order:
   *  1. Strip comments → scan for blocked keywords
   *  2. Check the query structure starts with SELECT
   *
   * @param sql - The SQL string generated by the LLM.
   * @returns A ValidationResult with `isValid` and an optional `reason`.
   *
   * @example
   * const { isValid, reason } = validator.validate('SELECT * FROM users');
   * if (!isValid) {
   *   console.error('Rejected:', reason);
   * }
   */
  validate(sql: string): ValidationResult {
    // Handle empty input
    if (!sql || sql.trim().length === 0) {
      return { isValid: false, reason: 'SQL query is empty.' };
    }

    // Handle the LLM's special "I cannot answer this" signal
    if (sql.trim().startsWith('-- UNABLE_TO_ANSWER')) {
      const reason = sql.trim().replace('-- UNABLE_TO_ANSWER:', '').trim();
      return {
        isValid: false,
        reason: `The AI could not generate a query for this question: ${reason}`,
      };
    }

    // ── Tier 1: Keyword Blocklist ─────────────────────────────────────────

    // First, strip SQL comments so attackers can't hide keywords in them.
    // Example attack: "SELECT 1; -- INSERT INTO ..." would otherwise pass.
    const sqlWithoutComments = this.stripComments(sql);

    // Reset regex lastIndex since we're reusing the compiled pattern
    this.blockedPattern.lastIndex = 0;
    const match = this.blockedPattern.exec(sqlWithoutComments);
    if (match) {
      return {
        isValid: false,
        reason: `Blocked keyword detected: ${match[1].toUpperCase()}. Only SELECT statements are allowed.`,
      };
    }

    // ── Tier 2: Structural Check ──────────────────────────────────────────

    const structureResult = this.checkStructure(sqlWithoutComments);
    if (!structureResult.isValid) {
      return structureResult;
    }

    // ── All checks passed ─────────────────────────────────────────────────
    return { isValid: true, reason: null };
  }

  /**
   * Removes both types of SQL comments from a query string:
   *  - Single-line comments: anything from "--" to end of line
   *  - Multi-line comments: anything between "/*" and "*​/"
   *
   * This prevents attackers from embedding blocked keywords in comments.
   *
   * @param sql - The raw SQL string.
   * @returns SQL string with all comments removed.
   */
  stripComments(sql: string): string {
    // Remove multi-line comments first: /* ... */
    // The [\s\S] matches any character including newlines.
    // The ? makes it non-greedy (stops at the FIRST *​/).
    let stripped = sql.replace(/\/\*[\s\S]*?\*\//g, ' ');

    // Remove single-line comments: -- anything until end of line
    stripped = stripped.replace(/--[^\r\n]*/g, ' ');

    // Normalise any resulting whitespace
    return stripped.replace(/\s+/g, ' ').trim();
  }

  /**
   * Checks that the SQL query is structurally a SELECT statement.
   *
   * This is not a full SQL parser — it checks the most important structural
   * property: that the first meaningful keyword is SELECT. This catches
   * cases like "UPDATE ... WHERE id IN (SELECT ...)" where the SELECT
   * comes second.
   *
   * It also rejects queries with multiple statements separated by semicolons,
   * which could be used to smuggle a mutation after a harmless SELECT.
   *
   * @param sql - SQL with comments already removed.
   * @returns ValidationResult indicating whether the structure is acceptable.
   */
  private checkStructure(sql: string): ValidationResult {
    const trimmed = sql.trim();

    // Reject multiple statements (e.g. "SELECT 1; DROP TABLE users")
    // We look for semicolons that are NOT at the very end of the string.
    const withoutTrailingSemi = trimmed.replace(/;\s*$/, '');
    if (withoutTrailingSemi.includes(';')) {
      return {
        isValid: false,
        reason: 'Multiple SQL statements detected. Only a single SELECT is allowed.',
      };
    }

    // The first word of the query must be SELECT.
    // \b ensures we match "SELECT" as a whole word, not "SELECTIVITY".
    if (!/^\s*SELECT\b/i.test(trimmed)) {
      // Determine the actual first keyword for a helpful error message
      const firstWord = trimmed.split(/\s+/)[0]?.toUpperCase() ?? 'UNKNOWN';
      return {
        isValid: false,
        reason: `Query must start with SELECT. Got: ${firstWord}`,
      };
    }

    return { isValid: true, reason: null };
  }
}
